### ISSUE TITLE
[back] add yamllint

### ISSUE THREAD

**Issue by Draeggon** [mdl29/scratchy#101]
link to yamllint [here](https://github.com/adrienverge/yamllint)

**Comment by js-all** [comment]
Is it really necessary ? I don't think we have this much yaml in the current code base

**Comment by Draeggon** [comment]
a lot of yaml file will come with open api

**Comment by yannis-mlgrn** [comment]
@Draeggon want to put linter every where 😂

**Comment by Draeggon** [comment]
@yannis-mlgrn I love them mdr

**Comment by yannis-mlgrn** [comment]
I see that 😂

**Comment by js-all** [comment]
I swear, fucking stop please

**Comment by Draeggon** [comment]
but they are incredible

**Comment by js-all** [comment]
yea that adds a whole application into th"e mix just to end up adding 3 new lines in a YALK file that might not even see the light of day because were not even sure to move to openAPI

**Comment by js-all** [comment]
i first need to understand wtf is openAPI

**Comment by Draeggon** [comment]
but in that case why is there a fucking issue for open api

**Comment by js-all** [comment]
GIVE ME FUCKING TIME TO READ PLEASE IM STILL AT THE HOMEPAGE OF THE GODDAMN WEBSITE

**Comment by Draeggon** [comment]
don't worry me too
