### ISSUE TITLE
[front] add css linter

### ISSUE THREAD

**Issue by Draeggon** [mdl29/scratchy#103]
Then the linter we can use is : [stylelint](https://github.com/stylelint/stylelint)

Some articles about it : 
- [How to name css classes](http://bdavidxyz.com/blog/how-to-name-css-classes/)
- [CSS Naming Conventions that Will Save You Hours of Debugging](https://www.freecodecamp.org/news/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849/)

**Depends on : #121**

**Comment by js-all** [comment]
Ok, calm the Fuck down on linters, please

**Comment by Draeggon** [comment]
yannis already approved it, too late

**Comment by js-all** [comment]
Yannis didn't write a single line of css

**Comment by Draeggon** [comment]
you read in my mind

**Comment by yannis-mlgrn** [comment]
Silence!  I did not do css because after gathering all the components and here I will add css

**Comment by Benvii** [comment]
I'm reviewing some of your code, we should choose a CSS guide style / naming convention.
We could try the BEM convention it's basic but it should to the job  (some people considered it a by ugly) :
http://getbem.com/introduction/

Then the linter we can use is : [postcss-bem-linter](https://github.com/postcss/postcss-bem-linter#postcss-bem-linter)

Some articles about it : 
- [How to name css classes](http://bdavidxyz.com/blog/how-to-name-css-classes/)
- [CSS Naming Conventions that Will Save You Hours of Debugging](https://www.freecodecamp.org/news/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849/)
