### ISSUE TITLE
[Front] room_list component is missing any way to quit a room

### ISSUE THREAD

**Issue by js-all** [mdl29/scratchy#109]

**Comment by Draeggon** [comment]
maybe a V2 feature

**Comment by js-all** [comment]
not sure if we really want to have no way of quitting a room, as of now users will be trapped forever.
Not that i wouldn't enjoy it.

**Comment by Draeggon** [comment]
when you say "quit a room" you mean go in another room or delete the room from your room list ?

**Comment by js-all** [comment]
delete the room from your list

**Comment by Draeggon** [comment]
ok seems fair
