### ISSUE TITLE
[Front] Use vue-cli and .vue files

### ISSUE THREAD

**Issue by Benvii** [mdl29/scratchy#113]
Depends on #90 

It's difficult to handle all components inside a single HTML file, template are hard to read as they are defined in string literals. That's why we should start using [vue-cli](https://cli.vuejs.org/) and `.vue` files.

**Comment by viandoxdev** [comment]
#90 has been merged so we should work on that this is probably one of the most important thing in V2.

**Comment by yannis-mlgrn** [comment]
I try to resolve this issue yesterday but I'm a nooby in vuejs , do you want resolve this issue @viandoxdev ?

**Comment by viandoxdev** [comment]
I can, but I need to know what setting we choose.
Like do we use typescript, what kind of linter / formatter we'll use, if we use class syntax or not.

**Comment by yannis-mlgrn** [comment]
> I can, but I need to know what setting we choose.
> Like do we use typescript, what kind of linter / formatter we'll use, if we use class syntax or not.

Yes we can use typescript it's a good idea but after idk. @Draeggon a suggestion ??

**Comment by viandoxdev** [comment]
started working on this, choose TS + vue 3.0 and default for the rest of the settings,
> ESlint error prevention only
> Babel + Typescript
> no class syntax
> separate config files

**Comment by viandoxdev** [comment]
if anyone has anything to say about those choices tel me.

**Comment by yannis-mlgrn** [comment]
No, nothing
