### ISSUE TITLE
[Front] Cleaner file organisation

### ISSUE THREAD

**Issue by Benvii** [mdl29/scratchy#121]
Files structure should be :
```
scratchy
|  front
   |  src
   |   | *.html
   |   | *.css
   |   | *.js
   |  package.json
   |  package-lock.json
   |  README.md
   | .gitignore ---> should be nodeJS / VUE gitignore
   |  nodes-modules/ (IGNORED)
```

Take care and also update the document link to files components : https://github.com/yannis-mlgrn/scratchy/blob/main/doc/frontend/frontend.md

**Comment by Benvii** [comment]
Maybe this gitignore : https://renatello.com/vue-js-gitignore/

**Comment by Benvii** [comment]
This issue is reopened as fixes commit where reverted by 
cf65a4b parent of e17ac2d211cc9983ca83c2d49c816dc16faed95a (revert commit)

**Comment by yannis-mlgrn** [comment]
how i do this ?

**Comment by Benvii** [comment]
@yannis-mlgrn just implement the ticket ;)
