### ISSUE TITLE
[doc] replace old emoji by a new version

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/scratchy#129]
in scratchy, to import a python, javaScript, emoji view. We need to create a directory with an emoji picture, but I have creating a site that hosts programming language emojies like python, javaScript, html and more.
The purpose of this issue is to replace the old emoji with a new version taken from my repository.

**Link :** 

-  https://github.com/yannis-mlgrn/codmoji

**Comment by mpsb** [comment]
Also looking to resolve this. I can only see the Python emoji on the main documentation. Where else should there be replacements?

**Comment by yannis-mlgrn** [comment]
Hey, all new emojies are in this repository

https://github.com/yannis-mlgrn/codmoji

In the repository you have  a link "copy here" and you should copy and paste to the Readme.md link to use new emojies
