### ISSUE TITLE
[doc] change api-documention

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/scratchy#130]
remove [api-documentation.md](https://github.com/mdl29/scratchy/blob/main/doc/backend/API-documentation.md) and replace by a link to the server readme on "How to play" line.

**Comment by mpsb** [comment]
Hello, @yannis-mlgrn! Please review the [forked repo](https://github.com/mpsb/scratchy) resolving this issue.

**Comment by yannis-mlgrn** [comment]
Hello, I look your code but you must make a pull request e.g : Resolve #130 change api documentation.
see here if you need help
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

Also thank for you participating in scratchy !

**Comment by mpsb** [comment]
Got it! Sorry, quite new to the whole open-source contribution. The pull request should be here: #132

**Comment by yannis-mlgrn** [comment]
No problem 😃
