### ISSUE TITLE
[doc] make a CONTRIBUTING.md

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/scratchy#131]

**Comment by Draeggon** [comment]
add the [discord](https://discord.gg/C9AJh4rd) in the read me

**Comment by yannis-mlgrn** [comment]
yes but it's a discord for LPH not for scratchy team ?
Yess I can create a role for scratchy team 👌

**Comment by Benvii** [comment]
Right no discord needed for now it's restricted to LPH, we will use it if we feel the need to do so

For instance take a look at the [CONTRIBUTING.md of tock](https://github.com/theopenconversationkit/tock/blob/master/CONTRIBUTING.md).

**Comment by ritorizo** [comment]
> add the [discord](https://discord.gg/C9AJh4rd) in the contributing.md

no
