### ISSUE TITLE
[Doc]  modifie our  profile image

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/scratchy#133]
UPDATE : 
replace on server Documentation in the update user line 
- curl -X PUT http://localhost:5000/api/user/607ae876f59d21d5a50ac3c9 -H "Content-Type: application/json" --data '{"pseudo":"un autre pseudo"}'

by :
-  curl -X PUT http://localhost:5000/api/user/607ae876f59d21d5a50ac3c9 -H "Content-Type: application/json" --data '{"pseudo":"un autre pseudo"**, profileImage : "link to profile image"**}'

**Comment by Draeggon** [comment]
@yannis-mlgrn we can update we just didn't write all the properties in the doc of put

**Comment by yannis-mlgrn** [comment]
@Draeggon, ok I'm waiting the update for finish scratchy service (#91).

**Comment by Draeggon** [comment]
@yannis-mlgrn  you missunderstood me come vocal #back

**Comment by yannis-mlgrn** [comment]
ok

**Comment by yannis-mlgrn** [comment]
**UPDATE : **
replace on server Documentation in the update user (curl -X PUT http://localhost:5000/api/user/607ae876f59d21d5a50ac3c9 -H "Content-Type: application/json" --data '{"pseudo":"un autre pseudo"}')  by :
-  curl -X PUT http://localhost:5000/api/user/607ae876f59d21d5a50ac3c9 -H "Content-Type: application/json" --data '{"pseudo":"un autre pseudo", profileImage : "link to profile image"}'

**Comment by mpsb** [comment]
Hello all. Created a PR for this: #137
