### ISSUE TITLE
[dependency] Adapt marshmallow-mongo engine to flask api-spec

### ISSUE THREAD

**Issue by Draeggon** [mdl29/scratchy#134]
[Marshmallow](https://github.com/marshmallow-code/marshmallow) create schema a bit different from [marshmallow-mongoengine](https://pypi.org/project/marshmallow-mongoengine/) we need to understand why and to adapt them for usage

**Comment by Draeggon** [comment]
i think we can somthing with [that](https://marshmallow-mongoengine.readthedocs.io/en/latest/_modules/marshmallow_mongoengine/convert.html)

**Comment by Benvii** [comment]
We should display a marshmallow object (defined ourselves) and an object generated by marshmallow-mongoengine and compare them. 

We need to detail what `a bit different from marshmallow-mongoengine` means, this ticket lack of information.

Define correctly the problem, what can't be done with marshmallow-mongo-engine objects ? Is there an exception raised somewhere ? What doesn't work ?

**Comment by Draeggon** [comment]
For now i don't know and i am experimenting with the lib to understand what happen.
I will update when i will have understand the problem.

**Comment by Draeggon** [comment]
model_build_obj is set to True but need to bet set to false like that:
```py
class RoomSchema(ModelSchema):
    class Meta:
        model = RoomModel
        model_build_obj = False
```
