### ISSUE TITLE
[deployment] Add Scratchy in docker compose environment

### ISSUE THREAD

**Issue by landerneRPi** [mdl29/scratchy#136]
Using the Dockerfile (or the image), add Scratchy server in docker-compose.yml file.
* expose port
* add environment variables (if needed)

Example of Dockerfile (in server directory):

```
FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .
RUN pip3 install -e .

ENV FLASK_APP=scratchy_server.app
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]

```

**Comment by Benvii** [comment]
Depends on #135

**Comment by Benvii** [comment]
Closed by https://github.com/mdl29/scratchy/pull/244
