### ISSUE TITLE
Create a kickstarter to give yanis english lesson

### ISSUE THREAD

**Issue by ritorizo** [mdl29/scratchy#138]
He needs it *(this is a test issue so no offense)*

**Comment by Draeggon** [comment]
genius

**Comment by landerneRPi** [comment]
> He need it _(this is a test issue so no offense)_

He needs it !

**Comment by yannis-mlgrn** [comment]
hum hum

**Comment by Draeggon** [comment]
i have tried but the project need a review from kickstarter staff maybe a ulul or a kisskissbangbang would bebetter
