### ISSUE TITLE
[Front] UI display roomId to endusers

### ISSUE THREAD

**Issue by js-all** [mdl29/scratchy#139]
End-users need to have access to room Ids as they need those IDs to join a room, we should display the roomIds somewhere.

**Comment by yannis-mlgrn** [comment]
this issue is done ?
@js-all mention it in #116 PR

**Comment by js-all** [comment]
> this issue is done ?
> @js-all mention it in #116 PR

its not

**Comment by js-all** [comment]
but its more of a design issue than code

**Comment by yannis-mlgrn** [comment]
okay

**Comment by js-all** [comment]
idea on how to implement it:
[image](https://i.imgur.com/zvcYwTy.png)
the share button (on the right of the activity bar) will copy the room id to the clipboard
(with a toast at the bottom of the page saying something like "room id copied to clipboard")

**Comment by yannis-mlgrn** [comment]
I'm bad in design, @js-all you can solve this issue please

**Comment by Benvii** [comment]
@yannis-mlgrn you can try 😉

**Comment by yannis-mlgrn** [comment]
if you want i will try this 😂
