### ISSUE TITLE
[back] Add Swagger-ui to current Swagger (Open API) implementation

### ISSUE THREAD

**Issue by landerneRPi** [mdl29/scratchy#142]
Add Swagger-ui.
Details on https://github.com/swagger-api/swagger-ui.

> By default, flask-apispec serves Swagger JSON at /swagger and Swagger UI at /swagger-ui. To override either URL, set the APISPEC_SWAGGER_URL and APISPEC_SWAGGER_UI_URL variables on the Flask application config, respectively.

**Comment by Draeggon** [comment]
The swagger ui linked is in js but our back is in python. Shoudn't we use a python swagger ui ?

**Comment by js-all** [comment]
> The swagger ui linked is in js but our back is in python. Shoudn't we use a python swagger ui ?

> swagger-ui-dist is a dependency-free module that includes everything you need to serve Swagger UI in a server-side project, or a single-page application that can't resolve npm module dependencies.

taken from the swagger ui README

**Comment by Draeggon** [comment]
> > The swagger ui linked is in js but our back is in python. Shoudn't we use a python swagger ui ?
> 
> > swagger-ui-dist is a dependency-free module that includes everything you need to serve Swagger UI in a server-side project, or a single-page application that can't resolve npm module dependencies.
> 
> taken from the swagger ui README

Ifyou go to the linked page [swagger-ui-dist](https://www.npmjs.com/package/swagger-ui-dist) you can see that dependency-free mean that the lib as no dependencies even if it is still a npm lib

**Comment by js-all** [comment]
> > > The swagger ui linked is in js but our back is in python. Shoudn't we use a python swagger ui ?
> > 
> > 
> > > swagger-ui-dist is a dependency-free module that includes everything you need to serve Swagger UI in a server-side project, or a single-page application that can't resolve npm module dependencies.
> > 
> > 
> > taken from the swagger ui README
> 
> Ifyou go to the linked page [swagger-ui-dist](https://www.npmjs.com/package/swagger-ui-dist) you can see that dependency-free mean that the lib has no dependencies even if it is still a npm lib

it doesn't matter as long as the thing doesn't base itself on node server workings, just because you need npm to install and use swagger-ui-dist doesn't mean that it only works with js

**Comment by js-all** [comment]
ok nvm swagger-ui-dist is meant to be used with node servers (my point about it needing npm but while it still could have been used in non js context still stands tho, just not iin the case of swagger-ui)

after looking a bit more in the github swagger-ui wiki:
> swagger-ui is meant for consumption by JavaScript web projects that include module bundlers, such as Webpack, Browserify, and Rollup. Its main file exports Swagger UI's main function, and the module also includes a namespaced stylesheet at swagger-ui/dist/swagger-ui.css.

so aparently it could be used on the frontend (not sure why tho, i don't even know what swagger-ui does).

**Comment by Draeggon** [comment]
Didn't know that npm lib could be use with python.  And swagger-ui put the request from the swagger in form

**Comment by js-all** [comment]
in "form" wdym ?
(and swagger ui cannot be used with a python backend (at first glance might have to look further into it (and yeah triple parenthesis why not)) its just that there could be any program written in js as a npm package while still being used with other languages, for example a linter)

**Comment by Draeggon** [comment]
here an [example](https://editor.swagger.io/)
left: the swagger
right: the form

**Comment by js-all** [comment]
looking at it like that swagger-ui should just take the yaml description and return a website, so no relation with the language the backend is written in

**Comment by Draeggon** [comment]
effectively didn't see it was that simple

**Comment by js-all** [comment]
ok after looking into it even deeper, swagger ui doesn't require to even understan the backend, just the swagger files

**Comment by Benvii** [comment]
We can try : https://pypi.org/project/flask-swagger-ui/ 
Seems to be easy to setup we just need to set the correct swagger path and it will be served by the backend.
