### ISSUE TITLE
[front] id system migration

### ISSUE THREAD

**Issue by Draeggon** [mdl29/scratchy#151]
the previous id system was:
id {
    $oid: "the id"
}
now:
id: "the id"

migration is required in all front document and the doc

**Comment by Benvii** [comment]
Will be needed only when #120 is merged.

**Comment by yannis-mlgrn** [comment]
@Draeggon, we must replace oid by id in frontend files ? Because now we  join them in scratchy service

**Comment by js-all** [comment]
> @Draeggon, we must replace oid by id in frontend files ? Because now we join them in scratchy service

*must we
isn't it already the case ? more like the frontend doesn't even know about ids and oids, it will when #179 will be resolved tho.

**Comment by Benvii** [comment]
As @js-all mentionned it's already the case according to the typeDef definition in the service : https://github.com/mdl29/scratchy/blob/main/front/src/js/service.js#L21 

But it's not well handled in components, oid still used in the following componnents : 
![odi](https://user-images.githubusercontent.com/1092728/120117859-9f2de000-c18f-11eb-93bd-2d2d745e8db1.png)

We need to keep this ticket open, someone might update the mentioned components.

**Comment by js-all** [comment]
this ticket doesn't really need to exists, because resolving #179 will need to do that already (wouldn't work otherwise).
We can keep the ticket and ill just add it to what my (coming soon™) PR resolves tho.

**Comment by Draeggon** [comment]
@js-all seems good to me to link it with your pr

**Comment by Benvii** [comment]
@js-all ideally mention it in your commit will autoclose this ticket

**Comment by Benvii** [comment]
Fixed by #230
