### ISSUE TITLE
[Front] make the app component use scratchy service

### ISSUE THREAD

**Issue by viandoxdev** [mdl29/scratchy#179]
this isn't gonna be annoying at all

**Comment by Benvii** [comment]
@js-all  Did you push it somewhere ? even if it's still work in progress

**Comment by js-all** [comment]
> @js-all  Did you push it somewhere ? even if it's still work in progress

Pretty sure I did on my fork

**Comment by Benvii** [comment]
Pushed here : https://github.com/Benvii/scratchy-1/tree/179_app_component 

Is it finished ?

**Comment by js-all** [comment]
> Pushed here : https://github.com/Benvii/scratchy-1/tree/179_app_component
> 
> Is it finished ?

not yet
