### ISSUE TITLE
[test] Add test hook before every test

### ISSUE THREAD

**Issue by Draeggon** [mdl29/scratchy#190]
we need to wipe out database before every test.
see in [doc](https://tavern.readthedocs.io/en/latest/basics.html#before-every-test-run)
it need to be put in test.py
needs #191

**Comment by Benvii** [comment]
I think @landerneRPi made some kind of makefile to do it, @landerneRPi can you confirm ?

**Comment by Draeggon** [comment]
Maybe but i think makefile only create things before all the testing test not after each test. Am I right ?

**Comment by Benvii** [comment]
We could use some kind of `make databaseclean` in the make file

**Comment by Draeggon** [comment]
look at #182
