### ISSUE TITLE
[back] add delete all method 

### ISSUE THREAD

**Issue by Draeggon** [mdl29/scratchy#191]
add delete all method in:
- [x] userres
- [x] roomres
- [x] messageres

needs #188

**Comment by Benvii** [comment]
Well it's somehing to erase all rooms/messages/users at once ? Do you think the front really need that, do you have a use case in mind ?

**Comment by Draeggon** [comment]
it is for test purpose and when a room would be delete we would need to delete all message filter by the roomId

**Comment by Benvii** [comment]
Maybe room deletion should handle it's messages deletion also ? could be an improvement of `DELETE /room/$id`

Also it a user is deleted do we need to delete all it's messages ?

**Comment by js-all** [comment]
> Maybe room deletion should handle it's messages deletion also ? could be an improvement of `DELETE /room/$id`
> 
> Also it a user is deleted do we need to delete all it's messages ?

room deletion should definitly delete its messages (how would anyone access them without te room)
but i would be more for keeping the messages of deleted users for context.

**Comment by Draeggon** [comment]
agree

**Comment by Draeggon** [comment]
but the id of the user should be remove from the rooms'  users list he is in

**Comment by js-all** [comment]
> but the id of the user should be remove from the rooms' users list he is in

and the user id should be removed from their messages (to avoid trying to get a deleted user's pseudo), it could be changed to something like `"removed"` to let the front know to not try to query the user

But, you can't delete user in front sooooooo V2
