### ISSUE TITLE
[tools] create a shell script to add test data into the server

### ISSUE THREAD

**Issue by ritorizo** [mdl29/scratchy#194]
Create an helper script to ~~create a venv and install dependencies~~, add testing data into the server.

**Comment by Benvii** [comment]
Is it a duplicate of #190 ? i think it's somehow linked

**Comment by Draeggon** [comment]
not #190 but #182 i think

**Comment by yannis-mlgrn** [comment]
The script is already present :  [test.py](https://github.com/mdl29/scratchy/blob/dev/server/scratchy_server/test/test.py)
for run the test file :
 ``` bash
<scratchy/server/scratchy-server/test>$ python test.py
```

**Comment by Draeggon** [comment]
test.py test the api but it erase the database after him, so it doesn't add testing data to the server
