### ISSUE TITLE
[Front] add a clipboard button on the share room id popup

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/scratchy#209]
I want to add a copy to clipboard button for copy directly the room id and share it more easier .
You can aslo add this clipboard [icon](https://feathericons.com/?query=clipboard).
I have found a tuto for make a clipboard button see [here](https://www.w3schools.com/howto/howto_js_copy_clipboard.asp)

**Comment by Draeggon** [comment]
do we really need an issue for this ? Can't you do it in the current issue ?

**Comment by yannis-mlgrn** [comment]
Is a new feature the #139 issue is just to display the room id but i can resolves this issue now in V1 version if you want

**Comment by Draeggon** [comment]
would be better

**Comment by yannis-mlgrn** [comment]
but first we need  #206 pull request to merge
