### ISSUE TITLE
[Doc] Error in README.md

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/scratchy#219]
we have two times "how to start it" in Readme.md, replace the first (link to template image) by "template image"
and in frontend README.md the link to how to start it is broken, it should be http://localhost:8000/src

**Comment by Benvii** [comment]
Tell in the user to go to front/src to start the python server and to open the website on port 8000.

**Comment by Benvii** [comment]
> Tell in the user to go to front/src to start the python server and to open the website on port 8000.

Fixed here : https://github.com/mdl29/scratchy/commit/74b0e9bbb4ba35cd2aaa766b1574c76c4e0dbdbe#diff-ec5b37b4c8473e3cd368497db6720457e3580a35112d9b94d85fa85e44f59b17R7
