### ISSUE TITLE
[front] Login screen / choose your pseudo

### ISSUE THREAD

**Issue by Benvii** [mdl29/scratchy#75]
Use case : 
> As a end user I need to choose my pseudo to use the app.
> As a end user I would like to automatically create an account if the pseudo doesn't exists.
> As a end user I would like to use the same account each time I use the app with the same pseudo.

We need a VueJS component that invites the user to type it's pseudo before using the app it should emit an event when the user wants to validate it's pseudo.

**Comment by Benvii** [comment]
test

**Comment by js-all** [comment]
not sure how to handle this, but ill try as there will be a special component to wrap around the API, this conponent won't directly talk with the back end, so here's how i think it should be done:
```html
<!-- the $event here is the username -->
<login v:on-login="login($event)"></login>
```
