### ISSUE TITLE
[back] Add python linter

### ISSUE THREAD

**Issue by Benvii** [mdl29/scratchy#78]
To enforce PEP8 coding style convention we should add a python linter to the backend code, such as Flake8 (might be the easiest one to add).

A github action that runs it could also be interesting, maybe this one : https://github.com/marketplace/actions/python-code-quality-and-lint

**Comment by Draeggon** [comment]
do we add Flake8 and let contributor check their syntax or do we write a script that check that every file respect PEP8 ?
