### ISSUE TITLE
[Front] Create scratchy service that contains methods for backend requests access.

### ISSUE THREAD

**Issue by landerneRPi** [mdl29/scratchy#91]
Methods for REST API in scratchy service (javascript) for:

- [x] Message

- [x] User

- [x] Room

Methods are:

- [x] get by id

- [x] update by id

- [x] delete by id

- [x] get all

Using axios

**Comment by js-all** [comment]
I'd go for fetch because it's native ? Should we go for axioq for compatibility ?

**Comment by Draeggon** [comment]
shoudn't you use open api ?

**Comment by js-all** [comment]
Isn't open API just specs ?
This is asking for how to send the request to the API, like we do with curl or insomnia currently

**Comment by yannis-mlgrn** [comment]
I believe fetch is native

**Comment by Benvii** [comment]
A lot of reasons why we should clearly use Axios over fetch are listed here : https://blog.logrocket.com/axios-or-fetch-api/

**Comment by yannis-mlgrn** [comment]
axios seems to be more easier and more convenient
