### ISSUE TITLE
[Front] Better css 

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/scratchy#93]
make a better css

**Comment by js-all** [comment]
What do you mean, my css is PERFECT

**Comment by yannis-mlgrn** [comment]
Yes, it's for my CSS.

**Comment by Benvii** [comment]
Issue description should be more precise, can you please list the components that needs CSS to be improved ?

**Comment by js-all** [comment]
i think none anymore since i merged #105

**Comment by js-all** [comment]
tho even my css can be largely improved

**Comment by Benvii** [comment]
Thanks @js-all closing the issue, we will reopen it with more details if needed.
