### ISSUE TITLE
[Doc] add insomnia export files 

### ISSUE THREAD

**Issue by yannis-mlgrn** [mdl29/scratchy#94]
use insomnia export files with yalm format

- [ ] make insomnia file with all request and environment variables

- [ ] export this file in yaml format

- [ ] add commentary to make a better documentation

**Comment by js-all** [comment]
To generate documentation or to test the api in insomnia ?

**Comment by yannis-mlgrn** [comment]
We can export a insomnia file in json or yaml format.  In this file have all request and configuration to send request more easily

**Comment by Draeggon** [comment]
in that case yaml is better because json don't allow commentary

**Comment by js-all** [comment]
you really want your linter don't you ?

**Comment by Draeggon** [comment]
you read in my mind

**Comment by yannis-mlgrn** [comment]
> in that case yaml is better because json don't allow commentary

Yes we say that yesterday

**Comment by Benvii** [comment]
It's unnecessary if you a swagger file (see #96 ) it can be used as input file for insomnia and it will generate a collection.

On the other hand, insomnia export files could be useful for environments and requests chaining details that aren't defined into the swagger file.

**Comment by Draeggon** [comment]
furthermore #96 is being done

**Comment by Benvii** [comment]
So we can close this issue ? everything will be done on #96

**Comment by js-all** [comment]
closing (can alwaysd be reopned later if needed).
