### ISSUE TITLE
[front] add vue linter

### ISSUE THREAD

**Issue by Draeggon** [mdl29/scratchy#98]
efficient and easy one: [https://eslint.vuejs.org/](https://eslint.vuejs.org/)

**Comment by js-all** [comment]
Not sure how it'll work right now because of our weird components in html files (not in .vue files) but Ill look into it.

**Comment by Draeggon** [comment]
in that case i will open another issue for an html linter

**Comment by yannis-mlgrn** [comment]
yes we can open a issue after gather all components to put in a .vue file or add a html linter

**Comment by Draeggon** [comment]
do we add a css linter ?

**Comment by yannis-mlgrn** [comment]
yes if you want to have a great code ^^

**Comment by Benvii** [comment]
> do we add a css linter ?

Issue was created here to add a CSS linter : #103

**Comment by Benvii** [comment]
> yes we can open a issue after gather all vuejs components to put in a .vue file or add a html linter

My vision : 
1. First step gather all component in one HTML file (and mutiple css files ) : #90
2. Switch to vue-cli and `.vue` files :  #113

**Comment by yannis-mlgrn** [comment]
okay i think is good idea

**Comment by viandoxdev** [comment]
just putting that here but no. Linters are bloat.
